<h1 style="font-size: 40px;">Gravitaional Waves DT Training </h1>

In [3]:
import pandas as pd
import numpy as np
from sklearn.model_selection import StratifiedKFold, RandomizedSearchCV, cross_validate, GridSearchCV
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier,GradientBoostingRegressor, GradientBoostingClassifier, HistGradientBoostingClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import make_scorer, accuracy_score, precision_score, recall_score
import matplotlib.pyplot as plt


features = pd.read_csv("features.csv", index_col=0)  # feature} columns only
targets = pd.read_csv("targets.csv", index_col=0)  
features = features.loc[targets.index]
feature_names = features.columns
targets=y = targets.values.ravel()

<h1 style="font-size: 32px;">One Decision Tree Model  </h1>

In [4]:
dt_model=DecisionTreeClassifier(min_samples_split=10)
scaler = StandardScaler()
features_scaled = scaler.fit_transform(features)
scores = cross_validate(dt_model, features_scaled, targets, cv = StratifiedKFold(n_splits=5), return_train_score=True)
scores

{'fit_time': array([0.13655829, 0.12705898, 0.17698073, 0.11037397, 0.0989666 ]),
 'score_time': array([0.00173211, 0.00150108, 0.0019033 , 0.0021925 , 0.00185013]),
 'test_score': array([0.5015, 0.501 , 0.4865, 0.515 , 0.488 ]),
 'train_score': array([0.872125, 0.877125, 0.878   , 0.881   , 0.878625])}

Feature Importance

In [13]:

dt_model.fit(features_scaled, targets)
importances = dt_model.feature_importances_
feature_names = (
    features.columns 
    if hasattr(features, "columns") 
    else [f"feature_{i}" for i in range(features_scaled.shape[1])]
)

importance_df = pd.DataFrame({
    "feature": feature_names,
    "importance": importances
}).sort_values("importance", ascending=False)

importance_df

             feature  importance
2     correlated_snr    0.260287
3               chi2    0.256661
1  cross_correlation    0.242580
0               norm    0.240472
4     snr_likelihood    0.000000

<h1 style="font-size: 32px;">Random Forest (Bagged Trees)  </h1>

In [5]:
rf_model = RandomForestClassifier(n_estimators=100, random_state=42, min_samples_split=10)
scores = cross_validate(rf_model, features_scaled, targets, cv = StratifiedKFold(n_splits=5), return_train_score=True)
scores

{'fit_time': array([2.58195662, 2.86223364, 2.64526486, 2.4462142 , 2.56028533]),
 'score_time': array([0.034513  , 0.03786111, 0.03907013, 0.04455853, 0.04218984]),
 'test_score': array([0.505 , 0.5035, 0.4915, 0.5   , 0.4825]),
 'train_score': array([0.991875, 0.989   , 0.99    , 0.990375, 0.98925 ])}

Feature Importance

In [12]:

rf_model.fit(features_scaled, targets)
importances = rf_model.feature_importances_
feature_names = (
    features.columns 
    if hasattr(features, "columns") 
    else [f"feature_{i}" for i in range(features_scaled.shape[1])]
)

importance_df = pd.DataFrame({
    "feature": feature_names,
    "importance": importances
}).sort_values("importance", ascending=False)

importance_df

             feature  importance
2     correlated_snr    0.255389
1  cross_correlation    0.252130
3               chi2    0.248423
0               norm    0.244059
4     snr_likelihood    0.000000

<h1 style="font-size: 32px;">Gradient Boosted Trees  </h1>

In [8]:
gb_model= GradientBoostingClassifier(max_depth=10, n_estimators=10)
scores = cross_validate(gb_model, features_scaled, targets, cv = StratifiedKFold(n_splits=5), return_train_score=True)
scores

{'fit_time': array([0.67178607, 0.58807063, 0.58328843, 0.57111168, 0.55862689]),
 'score_time': array([0.00227594, 0.00211549, 0.00204515, 0.00172448, 0.00169754]),
 'test_score': array([0.4845, 0.5045, 0.524 , 0.502 , 0.4885]),
 'train_score': array([0.72025 , 0.655375, 0.656625, 0.724125, 0.656625])}

Increasing the Number of Estimators

In [9]:
gb_model= GradientBoostingClassifier(max_depth=10, n_estimators=100)
scores = cross_validate(gb_model, features_scaled, targets, cv = StratifiedKFold(n_splits=5), return_train_score=True)
scores

{'fit_time': array([5.56443691, 5.72747874, 5.40908527, 5.58754611, 5.29914713]),
 'score_time': array([0.0080142 , 0.00718236, 0.00833583, 0.00884175, 0.00644302]),
 'test_score': array([0.488 , 0.5055, 0.515 , 0.516 , 0.487 ]),
 'train_score': array([0.962625, 0.954125, 0.95075 , 0.96175 , 0.96025 ])}

Feature Importance

In [11]:

gb_model.fit(features_scaled, targets)
importances = gb_model.feature_importances_
feature_names = (
    features.columns 
    if hasattr(features, "columns") 
    else [f"feature_{i}" for i in range(features_scaled.shape[1])]
)

importance_df = pd.DataFrame({
    "feature": feature_names,
    "importance": importances
}).sort_values("importance", ascending=False)

importance_df

             feature  importance
2     correlated_snr    0.263450
1  cross_correlation    0.256799
3               chi2    0.250373
0               norm    0.229378
4     snr_likelihood    0.000000

Hyperparamter Search of Gradient Boosted Trees

In [64]:
pd.set_option("display.max_rows", None)         # show all rows
pd.set_option("display.max_columns", None)      # show all columns
pd.set_option("display.max_colwidth", None)     # show full text in each column
pd.set_option("display.expand_frame_repr", True)  # don't wrap to multiple lines



parameters = {'max_depth':[6,10,15,None], 
              'max_iter':[100,200,500], 'learning_rate': [0.05, 0.1,0.3,0.5], 
              'early_stopping':[True, False]}

randomsearch = GridSearchCV(HistGradientBoostingClassifier(), parameters, cv = StratifiedKFold(n_splits=3, shuffle=True), \
                     verbose = 2, n_jobs = 4, return_train_score=True)
randomsearch.fit(features_scaled, targets)

scores = pd.DataFrame(randomsearch.cv_results_)
scoresCV = scores[['params','mean_test_score','std_test_score','mean_train_score']].sort_values(by = 'mean_test_score', \
                                                    ascending = False)
scoresCV

Fitting 3 folds for each of 96 candidates, totalling 288 fits

,params,mean_test_score,std_test_score,mean_train_score
28,"{'early_stopping': True, 'learning_rate': 0.3, 'max_depth': 10, 'max_iter': 200}",0.510300,0.005395,0.653850
6,"{'early_stopping': True, 'learning_rate': 0.05, 'max_depth': 15, 'max_iter': 100}",0.509299,0.008808,0.604600
3,"{'early_stopping': True, 'learning_rate': 0.05, 'max_depth': 10, 'max_iter': 100}",0.508998,0.011271,0.598800
30,"{'early_stopping': True, 'learning_rate': 0.3, 'max_depth': 15, 'max_iter': 100}",0.508300,0.004734,0.645150
26,"{'early_stopping': True, 'learning_rate': 0.3, 'max_depth': 6, 'max_iter': 500}",0.507900,0.004982,0.596650
8,"{'early_stopping': True, 'learning_rate': 0.05, 'max_depth': 15, 'max_iter': 500}",0.507799,0.004960,0.619902
16,"{'early_stopping': True, 'learning_rate': 0.1, 'max_depth': 10, 'max_iter': 200}",0.507401,0.007363,0.616000
10,"{'early_stopping': True, 'learning_rate': 0.05, 'max_depth': None, 'max_iter': 200}",0.507200,0.001829,0.629550
67,"{'early_stopping': False, 'learning_rate': 0.1, 'max_depth': 15, 'max_iter': 200}",0.506899,0.008460,0.850700
46,"{'early_stopping': True, 'learning_rate': 0.5, 'max_depth': None, 'max_iter': 200}",0.506800,0.003360,0.656850
14,"{'early_stopping': True, 'learning_rate': 0.1, 'max_depth': 6, 'max_iter': 500}",0.506800,0.004478,0.586851
36,"{'early_stopping': True, 'learning_rate': 0.5, 'max_depth': 6, 'max_iter': 100}",0.506699,0.004608,0.631500
51,"{'early_stopping': False, 'learning_rate': 0.05, 'max_depth': 10, 'max_iter': 100}",0.506600,0.003333,0.720350
12,"{'early_stopping': True, 'learning_rate': 0.1, 'max_depth': 6, 'max_iter': 100}",0.506500,0.003962,0.595250
1,"{'early_stopping': True, 'learning_rate': 0.05, 'max_depth': 6, 'max_iter': 200}",0.506199,0.004354,0.577400
22,"{'early_stopping': True, 'learning_rate': 0.1, 'max_depth': None, 'max_iter': 200}",0.506099,0.006758,0.622601
52,"{'early_stopping': False, 'learning_rate': 0.05, 'max_depth': 10, 'max_iter': 200}",0.505599,0.005798,0.776249
0,"{'early_stopping': True, 'learning_rate': 0.05, 'max_depth': 6, 'max_iter': 100}",0.505401,0.004811,0.575251
66,"{'early_stopping': False, 'learning_rate': 0.1, 'max_depth': 15, 'max_iter': 100}",0.505400,0.003413,0.787300
2,"{'early_stopping': True, 'learning_rate': 0.05, 'max_depth': 6, 'max_iter': 500}",0.505299,0.007555,0.567551
49,"{'early_stopping': False, 'learning_rate': 0.05, 'max_depth': 6, 'max_iter': 200}",0.505200,0.005656,0.730950
58,"{'early_stopping': False, 'learning_rate': 0.05, 'max_depth': None, 'max_iter': 200}",0.504999,0.008032,0.790600
39,"{'early_stopping': True, 'learning_rate': 0.5, 'max_depth': 10, 'max_iter': 100}",0.504601,0.004321,0.650450
15,"{'early_stopping': True, 'learning_rate': 0.1, 'max_depth': 10, 'max_iter': 100}",0.504301,0.004488,0.627950
18,"{'early_stopping': True, 'learning_rate': 0.1, 'max_depth': 15, 'max_iter': 100}",0.504100,0.004933,0.623000
27,"{'early_stopping': True, 'learning_rate': 0.3, 'max_depth': 10, 'max_iter': 100}",0.503700,0.002777,0.646050
44,"{'early_stopping': True, 'learning_rate': 0.5, 'max_depth': 15, 'max_iter': 500}",0.503700,0.008514,0.659999
57,"{'early_stopping': False, 'learning_rate': 0.05, 'max_depth': None, 'max_iter': 100}",0.503599,0.009133,0.731400
42,"{'early_stopping': True, 'learning_rate': 0.5, 'max_depth': 15, 'max_iter': 100}",0.503300,0.002384,0.659250
40,"{'early_stopping': True, 'learning_rate': 0.5, 'max_depth': 10, 'max_iter': 200}",0.503299,0.004383,0.652400
53,"{'early_stopping': False, 'learning_rate': 0.05, 'max_depth': 10, 'max_iter': 500}",0.503200,0.003654,0.867450
69,"{'early_stopping': False, 'learning_rate': 0.1, 'max_depth': None, 'max_iter': 100}",0.503199,0.004743,0.780650
78,"{'early_stopping': False, 'learning_rate': 0.3, 'max_depth': 15, 'max_iter': 100}",0.503199,0.009554,0.872900
70,"{'early_stopping': False, 'learning_rate': 0.1, 'max_depth': None, 'max_iter': 200}",0.502999,0.005677,0.854750
54,"{'early_stopping': False, 'learning_rate': 0.05, 'max_depth': 15, 'max_iter': 100}",0.502800,0.004197,0.733950
48,"{'early_stopping': False, 'learning_rate': 0.05, 'max_depth': 6, 'max_iter': 100}",0.502599,0.004963,0.672101
80,"{'early_stopping': False, 'learning_rate': 0.3, 'max_depth': 15, 'max_iter': 500}",0.502500,0.004208,0.998700
31,"{'early_stopping': True, 'learning_rate': 0.3, 'max_depth': 15, 'max_iter': 200}",0.502299,0.009614,0.653400
32,"{'early_stopping': True, 'learning_rate': 0.3, 'max_depth': 15, 'max_iter': 500}",0.501900,0.001472,0.639200
29,"{'early_stopping': True, 'learning_rate': 0.3, 'max_depth': 10, 'max_iter': 500}",0.501899,0.006982,0.640300
59,"{'early_stopping': False, 'learning_rate': 0.05, 'max_depth': None, 'max_iter': 500}",0.501700,0.006195,0.879450
7,"{'early_stopping': True, 'learning_rate': 0.05, 'max_depth': 15, 'max_iter': 200}",0.501600,0.006548,0.611450
50,"{'early_stopping': False, 'learning_rate': 0.05, 'max_depth': 6, 'max_iter': 500}",0.501599,0.008672,0.807800
68,"{'early_stopping': False, 'learning_rate': 0.1, 'max_depth': 15, 'max_iter': 500}",0.501499,0.011632,0.941550
23,"{'early_stopping': True, 'learning_rate': 0.1, 'max_depth': None, 'max_iter': 500}",0.501300,0.006743,0.633851
56,"{'early_stopping': False, 'learning_rate': 0.05, 'max_depth': 15, 'max_iter': 500}",0.501299,0.006846,0.880300
19,"{'early_stopping': True, 'learning_rate': 0.1, 'max_depth': 15, 'max_iter': 200}",0.501199,0.006229,0.640200
62,"{'early_stopping': False, 'learning_rate': 0.1, 'max_depth': 6, 'max_iter': 500}",0.501198,0.011676,0.872900
86,"{'early_stopping': False, 'learning_rate': 0.5, 'max_depth': 6, 'max_iter': 500}",0.500999,0.006040,0.998050
25,"{'early_stopping': True, 'learning_rate': 0.3, 'max_depth': 6, 'max_iter': 200}",0.500800,0.003572,0.616450
17,"{'early_stopping': True, 'learning_rate': 0.1, 'max_depth': 10, 'max_iter': 500}",0.500699,0.003779,0.619500
81,"{'early_stopping': False, 'learning_rate': 0.3, 'max_depth': None, 'max_iter': 100}",0.500699,0.008647,0.867650
9,"{'early_stopping': True, 'learning_rate': 0.05, 'max_depth': None, 'max_iter': 100}",0.500598,0.011085,0.611950
64,"{'early_stopping': False, 'learning_rate': 0.1, 'max_depth': 10, 'max_iter': 200}",0.500499,0.004483,0.845250
92,"{'early_stopping': False, 'learning_rate': 0.5, 'max_depth': 15, 'max_iter': 500}",0.500400,0.006248,1.000000
34,"{'early_stopping': True, 'learning_rate': 0.3, 'max_depth': None, 'max_iter': 200}",0.500400,0.003404,0.653700
85,"{'early_stopping': False, 'learning_rate': 0.5, 'max_depth': 6, 'max_iter': 200}",0.500299,0.005136,0.928850
79,"{'early_stopping': False, 'learning_rate': 0.3, 'max_depth': 15, 'max_iter': 200}",0.499599,0.006898,0.947450
75,"{'early_stopping': False, 'learning_rate': 0.3, 'max_depth': 10, 'max_iter': 100}",0.499599,0.013826,0.861800
21,"{'early_stopping': True, 'learning_rate': 0.1, 'max_depth': None, 'max_iter': 100}",0.499499,0.009087,0.642701
55,"{'early_stopping': False, 'learning_rate': 0.05, 'max_depth': 15, 'max_iter': 200}",0.499499,0.006598,0.787900
13,"{'early_stopping': True, 'learning_rate': 0.1, 'max_depth': 6, 'max_iter': 200}",0.499399,0.005841,0.587800
72,"{'early_stopping': False, 'learning_rate': 0.3, 'max_depth': 6, 'max_iter': 100}",0.499399,0.005354,0.804350
4,"{'early_stopping': True, 'learning_rate': 0.05, 'max_depth': 10, 'max_iter': 200}",0.499299,0.006555,0.598150
47,"{'early_stopping': True, 'learning_rate': 0.5, 'max_depth': None, 'max_iter': 500}",0.498898,0.011483,0.655800
63,"{'early_stopping': False, 'learning_rate': 0.1, 'max_depth': 10, 'max_iter': 100}",0.498801,0.005888,0.778850
33,"{'early_stopping': True, 'learning_rate': 0.3, 'max_depth': None, 'max_iter': 100}",0.498799,0.005443,0.652299
90,"{'early_stopping': False, 'learning_rate': 0.5, 'max_depth': 15, 'max_iter': 100}",0.498699,0.006879,0.911000
82,"{'early_stopping': False, 'learning_rate': 0.3, 'max_depth': None, 'max_iter': 200}",0.498699,0.009875,0.949000
61,"{'early_stopping': False, 'learning_rate': 0.1, 'max_depth': 6, 'max_iter': 200}",0.498599,0.011349,0.791750
94,"{'early_stopping': False, 'learning_rate': 0.5, 'max_depth': None, 'max_iter': 200}",0.498598,0.012437,0.984600
60,"{'early_stopping': False, 'learning_rate': 0.1, 'max_depth': 6, 'max_iter': 100}",0.498500,0.003929,0.729300
41,"{'early_stopping': True, 'learning_rate': 0.5, 'max_depth': 10, 'max_iter': 500}",0.498399,0.010495,0.650950
77,"{'early_stopping': False, 'learning_rate': 0.3, 'max_depth': 10, 'max_iter': 500}",0.498299,0.009675,0.998050
95,"{'early_stopping': False, 'learning_rate': 0.5, 'max_depth': None, 'max_iter': 500}",0.498099,0.010510,1.000000
35,"{'early_stopping': True, 'learning_rate': 0.3, 'max_depth': None, 'max_iter': 500}",0.497699,0.004051,0.646800
83,"{'early_stopping': False, 'learning_rate': 0.3, 'max_depth': None, 'max_iter': 500}",0.497699,0.007432,0.998350
91,"{'early_stopping': False, 'learning_rate': 0.5, 'max_depth': 15, 'max_iter': 200}",0.497599,0.013152,0.982650
5,"{'early_stopping': True, 'learning_rate': 0.05, 'max_depth': 10, 'max_iter': 500}",0.497500,0.005568,0.614149
87,"{'early_stopping': False, 'learning_rate': 0.5, 'max_depth': 10, 'max_iter': 100}",0.497300,0.008234,0.903950
71,"{'early_stopping': False, 'learning_rate': 0.1, 'max_depth': None, 'max_iter': 500}",0.497099,0.005467,0.939800
24,"{'early_stopping': True, 'learning_rate': 0.3, 'max_depth': 6, 'max_iter': 100}",0.496899,0.008883,0.618250
38,"{'early_stopping': True, 'learning_rate': 0.5, 'max_depth': 6, 'max_iter': 500}",0.496800,0.000629,0.626101
65,"{'early_stopping': False, 'learning_rate': 0.1, 'max_depth': 10, 'max_iter': 500}",0.496799,0.006214,0.932150
11,"{'early_stopping': True, 'learning_rate': 0.05, 'max_depth': None, 'max_iter': 500}",0.496399,0.009097,0.595651
20,"{'early_stopping': True, 'learning_rate': 0.1, 'max_depth': 15, 'max_iter': 500}",0.496300,0.000628,0.631150
89,"{'early_stopping': False, 'learning_rate': 0.5, 'max_depth': 10, 'max_iter': 500}",0.496200,0.008513,1.000000
84,"{'early_stopping': False, 'learning_rate': 0.5, 'max_depth': 6, 'max_iter': 100}",0.496198,0.012467,0.842000
88,"{'early_stopping': False, 'learning_rate': 0.5, 'max_depth': 10, 'max_iter': 200}",0.496099,0.008062,0.979400
93,"{'early_stopping': False, 'learning_rate': 0.5, 'max_depth': None, 'max_iter': 100}",0.495999,0.007602,0.912350
76,"{'early_stopping': False, 'learning_rate': 0.3, 'max_depth': 10, 'max_iter': 200}",0.495899,0.008601,0.940150
73,"{'early_stopping': False, 'learning_rate': 0.3, 'max_depth': 6, 'max_iter': 200}",0.495599,0.008596,0.877850
37,"{'early_stopping': True, 'learning_rate': 0.5, 'max_depth': 6, 'max_iter': 200}",0.495500,0.004989,0.628100
43,"{'early_stopping': True, 'learning_rate': 0.5, 'max_depth': 15, 'max_iter': 200}",0.495299,0.003977,0.657950
45,"{'early_stopping': True, 'learning_rate': 0.5, 'max_depth': None, 'max_iter': 100}",0.493401,0.006194,0.656700
74,"{'early_stopping': False, 'learning_rate': 0.3, 'max_depth': 6, 'max_iter': 500}",0.492599,0.005006,0.974050